import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    params,
    children,
}: Readonly<{
    params: { domain: string };
    children: React.ReactNode;
}>) {
    const domain = decodeURIComponent(params.domain);

    return (
        <html lang="en">
            <body className={inter.className}>
                <h1>{domain}</h1>
                {children}
            </body>
        </html>
    );
}
