import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
const inter = Inter({ subsets: ["latin"] });
import { getShopFromDomain, getShopFromSlug } from "@/actions/shop";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const headersList = headers();
    const requestUrl = headersList.get("host");
    let shopDetails = null;
    if (requestUrl) {
        if (
            requestUrl.includes(process.env.NEXT_PUBLIC_ROOT_DOMAIN as string)
        ) {
            const slug = requestUrl.replace(
                process.env.NEXT_PUBLIC_ROOT_DOMAIN as string,
                ""
            );
            shopDetails = getShopFromSlug(slug);
        } else {
            shopDetails = getShopFromDomain(requestUrl);
        }
    } else {
        redirect("/404");
    }

    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
