import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import NotFound from "./not-found";
const inter = Inter({ subsets: ["latin"] });
import { getShopInfo } from "@/actions/shop";
export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const shopDetails = await getShopInfo();
    if (shopDetails == null) {
        return (
            <html>
                <body>
                    <NotFound />
                </body>
            </html>
        );
    }
    return (
        <html lang="en">
            <body className={inter.className}>{children}</body>
        </html>
    );
}
